name: backend-base

on:
  push:
    # Publish `dev` as Docker `latest` image.
    branches:
      - main
    paths:
      - 'backend/base/**'

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: echo "To-Do Add Running Tests"
          
  build:
    # Ensure test job passes before pushing image.
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./backend/base
          platforms: linux/amd64,linux/arm64
          push: true
          tags: reallibrephotos/librephotos-base:dev
